apps/blogango/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change, password_reset
from django.contrib.sitemaps import GenericSitemap

from blogango import feeds
from blogango.models import BlogEntry

blog_info_dict = {
    'queryset': BlogEntry.objects.filter(is_published=True),
    'date_field': 'created_on',
}
sitemaps = {
    'blog': GenericSitemap(blog_info_dict, priority=0.5)
}

urlpatterns = patterns('blogango.views',
    url(r'^welcome/$', 'welcome', name='blogango_welcome'),
    url(r'^install/$', 'install_blog', name='blogango_install'),
    url(r'^preferences/$', 'edit_preferences', name='blogango_edit_preferences'),
     
    url(r'^$', 'index', name='blogango_index'),
    url(r'^page/(?P<page>\d+)/$', 'index',  name='blogango_page'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[-\w]+)/$', 'details', name='blogango_details'),
    url(r'^new/$', 'create_entry', name='blogango_create'),
    url(r'^blogroll/$', 'create_blogroll', name='blogango_blogroll'),
    url(r'^moderate/$', 'moderate_comments', name='blogango_mod_comments'),
    url(r'^entries/$', 'mod_entries', name='blogango_mod_entries'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$','tag_details', name='blogango_tag_details'),
    url(r'^manage/$', 'manage', name='blogango_manage'),
    url(r'^edit/(?P<entry_id>\d+)/$', 'edit_entry', name='blogango_edit_entry'),
    url(r'^comment/(?P<comment_id>\d+)/$', 'comment_details', name='blogango_comment_details'),
    url(r'^author/(?P<username>[\w.@+-]+)/$', 'author', name='blogango_author'),
    
    url(r'^admin/$', 'admin_dashboard', name='blogango_admin_dashboard'),
    url(r'^admin/entry/new/$', 'admin_entry_edit', name='blogango_admin_entry_new'),
    url(r'^admin/entry/edit/(?P<entry_id>\d+)/$', 'admin_entry_edit', name='blogango_admin_entry_edit'),
    url(r'^admin/entry/manage/$', 'admin_manage_entries', name='blogango_admin_entry_manage'),
    url(r'^admin/comments/manage/$', 'admin_manage_comments', name='blogango_admin_comments_manage'),
    url(r'^admin/preferences/edit/$', 'admin_edit_preferences', name='blogango_admin_edit_preferences'),
    url(r'^admin/comment/approve/(?P<comment_id>\d+)/$', 'admin_comment_approve', name='blogango_admin_comment_approve'),
    url(r'^admin/comment/block/(?P<comment_id>\d+)/$', 'admin_comment_block', name='blogango_admin_comment_block'),
)

#search view
urlpatterns += patterns('blogango.search',
    url(r'^search/$', 'search', name = 'search'),        
)

# sitemap.xml
urlpatterns += patterns('django.contrib.sitemaps.views',
    url(r'^sitemap\.xml$', 'sitemap', {'sitemaps': sitemaps}),        
)     

# Archive view
urlpatterns += patterns('blogango.views',
    url(r'^archive/(?P<year>\d+)/(?P<month>\w+)/$', 'monthly_view', name='blogango_archives')
)

#urlpatterns += patterns('django_xmlrpc.views',
#    url(r'^xmlrpc/$', 'handle_xmlrpc', {}, name='xmlrpc'),
#)

feeds = {'latest': feeds.main_feed, 'tag':feeds.CatFeed}
# feeds = {'latest': feeds.main_feed}
urlpatterns += patterns('',
    url(r'^rss/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, name='blogango_feed')
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

handler500 = 'netconference.views.server_error'

from account.forms import SignupForm

from socialauth import urls as socialauth_urls

urlpatterns = patterns('',
    url(r'^traffic_geyser/', include('traffic_geyser.urls')),
    url(r'^amfservices/$', 'amfservices.gateway.gw'),
    url(r'^amfhttp/', include('amfservices.urls')),
    url(r'^vmail/', include('vmail_new.urls')),
    url(r'^wsdl/', include('amfservices.urls')),
    url(r'^60/$', "account.views.sixty_day_coupon", name="sixty_day_coupon"),
    url(r'^$', direct_to_template, {"template": "newer_homepage.html"}, name="home"),
    
	url(r'^landing/$', direct_to_template, {"template": "landing.html",
                                                'extra_context':{'form':SignupForm(),
                                                                 'INCLUDE_ANALYTICS': settings.INCLUDE_ANALYTICS}
                                                }, name="landing"),
	url(r'^landingvideo/$', direct_to_template, {"template": "landing_video.html",
                                                'extra_context':{'form':SignupForm()}
                                                }, name="landingvideo"), 												
       
    url(r'^admin/invite_user/generated_email/$', 'signup_codes.views.show_generated_email', name="generated_email"), 
    url(r'^admin/invite_user/$', 'signup_codes.views.admin_invite_user', name="admin_invite_user"),
    
    url(r'^robots.txt$', include('robots.urls')),
    
    url(r'^admin/(.*)', admin.site.root),
    
    url(r'^invest/', 'contact_form.views.invest', name="invest"),
    url(r'^meeting/(?P<username>[\w\._-]+)/$', 'conferencing.views.conference_session_quick', name='conference_session_quick'),
    url(r'^meeting/setx/(?P<urlhash>[-0-9A-Za-z_-]+)/$', 'conferencing.views.conference_session2', name='conference_session2'),
#    url(r'^meeting/setx/(?P<urlhash>[-0-9A-Za-z_-]+)/$', 'conferencing.views.conference_flex', name='conference_flex'),
    url(r'^meeting/set/(?P<urlhash>[-0-9A-Za-z_-]+)/$', 'conferencing.views.conference_flash', name='conference_flash'),
    url(r'^meeting/set2/(?P<urlhash>[-0-9A-Za-z_-]+)/$', 'conferencing.views.conference_session', name='conference_session'),
    url(r'^file/(?P<urlhash>[-0-9A-Za-z_-]+)/$', 'files.views.file_detail', name='file_detail'),
    
 
    
    
    url(r'^crossdomain.xml$', 'flashpolicies.views.simple', { 'domains': ['www.localhacks.com', 'netconference.tv', 'iftest.netconference.com', 'www.netconference.tv', 'netconference.com', 'www.netconference.com', 'dev.netconference.com', 'beta.netconference.com', 'nxtgenlabs.tv', 'www.nxtgenlabs.tv', 'nuriche.tv', 'www.nuriche.tv', 'efusjonmeeting.illusion.webfactional.com', 'efusjonmeeting.com', 'www.efusjonmeeting.com', 'nxtgendemo.tv', 'www.nxtgendemo.tv', '208.109.252.110', "*", ""] }),
    url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    
    url(r'^about/', include('about.urls')),
    url(r'^account/signup/promo/', 'signup_codes.views.signup', name='signup_promo'),
    url(r'^account/', include('account.urls')),
    url(r'^bbauth/', include('bbauth.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^tags/', include('tag_app.urls')),
    url(r'^connections/', include('friends_app.urls')),
    url(r'^notices/', include('notification.urls')),
    url(r'^messages/', include('messages.urls')),
    url(r'^announcements/', include('announcements.urls')),
    url(r'^comments/', include('threadedcomments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^avatar/change/$', 'account.views.avatar_change', name='avatar_change'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^flag/', include('flag.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^conferencing/', include('conferencing.urls')),
    url(r'^messaging/', include('vmail.urls')),
    url(r'^contact/', include('contact_form.urls')),
    url(r'^subscription/', include('subscription.urls')),
    url(r'^payment/auth/verify/fnord/selection/', include('paypal.standard.ipn.urls')),
    url(r'^features/', include('features.urls')),
    url(r'^files/', include('files.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^billing/', include('billing.urls')),
    url(r'^netsign/', include('netsign.urls')),
    url(r'^affiliate/', include('affiliate.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^activity/', include('activitystream.urls')),
    url(r'^rest/', include('restrictions.urls')),
    url(r'^projects/', include('project.urls')),
    url(r'^store/', include('store.urls')),
    url(r'^reporting/', include('reporting.urls')),
    url(r'^meter/', 'restrictions.views.show_context', name='usage_meter'),
    url(r'^total_usage/', 'restrictions.views.total_usage', name='total_usage'),
    url(r'^camtest/$', direct_to_template, {"template": "conferencing/camtest.html"}, name="camtest"),
    url(r'^googlehostedservice.html/$', 'googleapps.views.verify', name='googleverify'),
    url(r'^openid/', include('django_openid_auth.urls')),
    url(r'^integrate/', include('integrate.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^android/', include('android.urls')),
    url(r'^workgroups/', include('tribes.urls')),
    url(r'^blog/', include('blogango.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^comment/(?P<content_type>\d+)/(?P<object_id>\d+)/$', 'threadedcomments_extras.views.comment', name="tc_comment"),
    url(r'^comment/(?P<content_type>\d+)/(?P<object_id>\d+)/(?P<parent_id>\d+)/$', 'threadedcomments_extras.views.comment', name="tc_comment_parent"),
    url(r'^zendesk/login/$', 'zendesk.views.authorize', name="zendesk_authorize"),
    url(r'^oauth2callback/$', 'friends_app.views.oauth_callback', name="friends_oauth_callback"),
    url(r'^yahoo2callback/$', 'friends_app.views.yahoo_callback', name="yahoo_callback"),
    url(r'^recurly_notification/$', 'subscription.views.recurly_notification', name='recurly_notification'),
    url(r'^socialauth/', include(socialauth_urls)),
    url(r'^landingpages/', include('landingpages.urls')),
    url(r'^testsocialauth/$', direct_to_template, {"template":"socialauth/after_signup2.html"}, name="aftersignup2.html"),
    url(r'^followup/$', 'about.views.followup', name='follow_up'),
    url(r'^tutorial/$', direct_to_template, {"template":"newer_tutorial.html"}, name="tutorial"),
    url(r'^track_social_signup/$', direct_to_template, {"template":"newer_signup_complete.html"}, name="social_signup_complete"),
    url(r'^track_cc_signup/$', direct_to_template, {"template":"newer_signup_complete1.html"}, name="cc_signup_complete"),
    url(r'^autoresponder/', include('autoresponder.urls')),
    url(r'^create_account_intermediate/$', direct_to_template, {"template":"create_account_intermediate.html"}, name="create_account_intermediate"),
    url(r'^googledriver/', include('googledriver.urls')),
    #This should be the last as it is essentially a catchall thingie.
    url(r'^(?P<username>[\w\._-]+)/$', 'schedule.views.calendar', name="user_dashboard"),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'staticfiles.views.serve'),

    )

apps/blogango/forms.py
from django.contrib.auth.models import User
from django import forms

from blogango.models import Blog, BlogRoll, BlogEntry

class WideTextArea(forms.Textarea):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('attrs',{}).update({'rows': '20', 'cols':'80'})
        super(WideTextArea, self).__init__(*args, **kwargs)

#class EntryForm(forms.Form):
#    title = forms.CharField(max_length=100, required=False) 
#    text = forms.CharField(widget=WideTextArea, label='Entry')
#    slug = forms.CharField(max_length=100, required=False) 
#    tags = forms.CharField(max_length=100, required=False)
#    is_page = forms.BooleanField(initial=False, label='Is it a page?', required=False)
#    comments_allowed = forms.BooleanField(initial=True, label='Are comments allowed?', required=False)
#    is_rte = forms.BooleanField(initial=True, label='Use Rick Text?', required=False)

class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EntryForm, self).__init__(*args, **kwargs)
        self.fields['created_by'].queryset = User.objects.filter(is_staff=True)
    
    title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'size':'40'}))
    text = forms.CharField(widget=WideTextArea(attrs={'class': 'resizable'}))
    
    class Meta:
        model = BlogEntry
        exclude = ('slug', 'summary')

class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), label='Comment')
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'textfield'}))
    url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'textfield'})) 
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'textfield'}))

class TagForm(forms.Form):
    tag_txt = forms.CharField(max_length=100, label='Tag as') 

class InstallForm(forms.ModelForm):
    
    class Meta:
        model = Blog
        exclude = ('entries_per_page', 'recents', 'recent_comments')

class PreferencesForm(forms.ModelForm):
    
    class Meta:
        model = Blog
        #exclude = ('title', 'tag_line')
        
class BlogForm(forms.ModelForm):
    
    class Meta:
        model = BlogRoll
        exclude = ('is_published',)   
        

apps/blogango/templates/blogango/admin/base.html
{% load blogango_filters %}
{% blogango_extra_context %}

<!doctype html>
<html>
<head>
  {% block html_head %}

  <title>{% block title %}{% endblock %} &mdash; {{ blog.title }} {{ _("Administration") }}</title>

  <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}blogango/admin/preview.css">
  <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}blogango/admin/style.css">

  <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}blogango/js/jquery.autocomplete.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}blogango/js/jquery.textarearesizer.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}blogango/js/Admin.js"></script>
  {% endblock %}
  {% block page_head %}{% endblock %}
</head>
<body>
  <div class="header">
    <div class="title">{{ blog.title }} Administration</div>
    <div class="metanav">
      <a href="{% url blogango_index %}">{{ _("View Blog") }}</a> |
      <a href="{% url admin:logout %}">{{ _("Logout") }}</a>
	  {% comment %}
	  <a href="{# url_for('account/index')|e #}">{{ _("My Account") }}</a> |
      <a href="{# url_for('admin/help') #}">?</a>
      {% endcomment %}
    </div>
  </div>
  <div class="body">
    <ul class="navbar standalonebar">
      {% url blogango_admin_dashboard as dashboard_url %}
      <li {% ifequal request.path dashboard_url %}class="active"{% endifequal %}>
          <a href="{{ dashboard_url }}">{{ _("Dashboard") }}</a>
      </li>
      {% url blogango_admin_entry_new as write_url %}
      <li {% ifequal request.path write_url %}class="active"{% endifequal %}>
          <a href="{{ write_url }}">{{ _("Write") }}</a>
      </li>
      {% url blogango_admin_entry_manage as manage_entry_url %}
      <li {% ifequal request.path manage_entry_url %}class="active"{% endifequal %}>
          <a href="{{ manage_entry_url }}">{{ _("Manage") }}</a>
      </li>
      {% url blogango_admin_comments_manage as manage_comments_url %}
      <li {% ifequal request.path manage_comments_url %}class="active"{% endifequal %}>
          <a href="{{ manage_comments_url }}">{{ _("Comments") }}</a>
      </li>
      {% url blogango_admin_edit_preferences as edit_preferences_url %}
      <li {% ifequal request.path edit_preferences_url %}class="active"{% endifequal %}>
          <a href="{{ edit_preferences_url }}">{{ _("Options") }}</a>
      </li>
    </ul>
    {% block subnavbar %}{% endblock %}
    <div class="contents">
      {% block contents %}{% endblock %}
    </div>
  </div>
  <div class="footer">
    <p>
        <a href="http://{{ site.domain }}/">{{ site.name }}</a> 
        Powered by blogango | &copy; 2010 by {{ site.name }}
    </p>
  </div>
</body>
</html>

apps/blogango/templates/blogango/admin/edit_entry.html
{% extends "blogango/admin/base.html" %}

{% block page_head %}
<!-- Load TinyMCE -->
<script type="text/javascript" src="{{ MEDIA_URL }}blogango/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}blogango/js/jquery-tinymce.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('div.tinymce textarea').tinymce({
			// Location of TinyMCE script
			script_url : '{{ MEDIA_URL }}/blogango/js/tiny_mce/tiny_mce.js',

			// General options
			theme : "advanced",
			plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

			// Theme options
			theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
            forced_root_block: false,

		});
	});
</script>
<!-- /TinyMCE -->
{% endblock %}

{% block title %}
    {% if entry %}
        Editing entry:: {{ entry_form.initial.title }}
    {% else %}
        New Entry
    {% endif %}
    &#8203;{{ title_suffix }}
{% endblock %}
{% block subnavbar %}
    <ul class="ctxnavbar">
      <li{% if not is_page %} class="active"{% endif %}>
          <a href="{{ request.path }}">Entry</a>
      </li>
      <li{% if is_page %} class="active"{% endif %}>
          <a href="{{ request.path }}?page">Page</a>
      </li>
    </ul>
{% endblock %}
{% block contents %}
      <div class="notification-messages">
	    {% if is_done %}
	        <div class="message message-info">Blog entry saved successfully</div>
	    {% endif %}
      </div>
    {% if entry %}
        <h1>
            {{ entry.title }} &mdash; &#8203; Edit Entry
            {% if entry.is_published %}
                <a href="{{ entry.get_absolute_url }}" class="preview">{{ _("View Entry") }}</a>
            {% else %}
                <a href="{{ entry.get_absolute_url }}?preview" class="preview">{{ _("Preview Entry") }}</a>
            {% endif %}
        </h1>
    {% endif %}
    {% if entry_form.errors %}
        Please correct the following errors:
        <ul class="errors">
            {% for field, error in entry_form.errors.iteritems %}
                <li>{{ field }} {{ error.as_text }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST">
		<div class="formbox formbox-title">
		      <h3><label for="id_title">Title</label></h3>
		      {{ entry_form.title }}
		</div>
        <div class="formbox">
            <h3 onclick="$('div.tinymce textarea').tinymce('toggle');"><label for="id_tinymce">TinyMCE</label></h3>
        </div>
		<div class="formbox tinymce">
		      <h3><label for="id_text">Text</label></h3>
		      {{ entry_form.text }}
		</div>
		<div class="formbox">
		      <h3><label for="id_text_markup_type">Markup Parser</label></h3>
		      {{ entry_form.text_markup_type }}
		</div>
		<div class="formbox">
		      <h3><label for="id_tags">Tags</label></h3>
		      {{ entry_form.tags }}
		</div>
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_created_by">Author</label></h3>
		      {{ entry_form.created_by }}
		</div>	
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_meta_keywords">Keywords</label></h3>
		      {{ entry_form.meta_keywords }}
		</div>
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_meta_description">Description</label></h3>
		      {{ entry_form.meta_description }}
		</div>
		<div class="formbox">
		      <h3><label for="id_comments_allowed">Allow Comments?</label></h3>
		      {{ entry_form.comments_allowed }}
		</div>
		{% if is_page %}
		    <input type="hidden" name="page" value="1" />
		{% endif %}
		<div class="secondary">
		  <div class="actions">
		    <input type="submit" value="{% if entry.is_published %}Unpublish{% else %}Save{% endif %}" name="save">
		    <input type="submit" value="Save and Publish" name="publish">
		    <input type="reset" value="Cancel" name="cancel">
		  </div>
		</div>
	</form>
{% endblock %}

apps/blogango/templates/blogango/admin/edit_preferences.html
{% extends "blogango/admin/base.html" %}
{% block title %}{{ _("Basic Options") }}{% endblock %}
{% block contents %}
  <h1>{{ _("Basic Options") }}</h1>
  <p>
    From here you can configure the basic blog settings like the blog
    title and tagline.
  </p>
  <div class="notification-messages">      
    {% if done %}
        <div class="message message-info">Preferences saved successfully</div>
    {% endif %}
  </div>  
	{% if form.errors %}
	    Please correct the following errors:
	    <ul class="errors">
	        {% for field, error in form.errors.iteritems %}
	            <li>{{ field }} {{ error.as_text }}</li>
	        {% endfor %}
	    </ul>
	{% endif %}
  <form method="POST">
      <dl>
	    <dt>
	      <label for="id_title">Blog title</label>
	    </dt>
	    <dd>
	      {{ form.title }}
	    </dd>
	    <dt>
	      <label for="id_tag_line">Blog tagline</label>
	    </dt>
	    <dd>
	      {{ form.tag_line }}
	    </dd>
	    <dt>
	      <label for="id_entries_per_page">Entries per page</label>
	    </dt>
	    <dd>
	      {{ form.entries_per_page }}
	    </dd>
	    <dt>
	      <label for="id_recents">Number of recent entries</label>
	    </dt>
	    <dd>
	      {{ form.recents }}
	    </dd>
	    <dt>
	      <label for="id_recent_comments">Number of recent comments</label>
	    </dt>
	    <dd>
	      {{ form.recent_comments }}
	    </dd>
	  </dl>
	    <div class="actions">
	      <input type="submit" value="{{ _('Save') }}">
	    </div>
  </form>
{% endblock %}

apps/blogango/templates/blogango/admin/index.html
{% extends "blogango/admin/base.html" %}
{% load i18n %}
{% block title %}{{ _("Dashboard") }}{% endblock %}
{% block contents %}
  <div class="dashboard">
    <h1>{{ _("Dashboard") }}</h1>
    <div class="panel">
      <div class="text">
        <p>
          Howdy. Welcome to the administration interface, {{ request.user.username }}.
          You have written <strong>{{ request.user.blogentry_set.count }}</strong> post{{ request.user.blogentry_set.count|pluralize }} so far.
      </div>
      <h2>{{ _('Quickstart') }}</h2>
      <ul>
        <li><a href="{% url blogango_admin_entry_new %}">{{ _("New Entry") }}</a>
        <li><a href="{% url blogango_admin_comments_manage %}">{{ _("Moderate Comments") }}</a>
        <li><a href="{% url blogango_admin_entry_manage %}">{{ _("Manage Entries") }}</a>
        <li><a href="{% url blogango_admin_edit_preferences %}">{{ _("Configure blogango") }}</a>
      </ul>
    </div>
    <div class="links">
      {% if recent_drafts %}
      <h2>{{ _("Drafts") }}</h2>
      <ul class="drafts">
      {% for draft in recent_drafts %}
        <li>
            <a href="{{ draft.get_edit_url }}">{{ draft.title }}</a>
            <span class="meta">[<a href="{{ draft.get_absolute_url }}">{{ _('show') }}</a>]</span>,
            {{ draft.created_on }}
        </li>
      {% endfor %}
      </ul>
      {% endif %}
      {% if recent_entries %}
      <h2>{{ _("Recent Posts") }}</h2>
      <ul class="last_posts">
      {% for post in recent_entries %}
        <li>
            <a href="{{ post.get_edit_url }}">{{ post.title }}</a>
            <span class="meta">[<a href="{{ post.get_absolute_url }}">{{ _('show') }}</a>]</span>,
          {{ post.created_on }}
      {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="clear"></div>
  </div>
{% endblock %}

apps/blogango/templates/blogango/admin/manage_comments.html
{% extends "blogango/admin/base.html" %}
{% block title %}{{ _("Manage Comments") }}{% endblock %}
{% block contents %}
  <h1>{{ _("Manage Comments") }}</h1>
    <ul class="comments">
    {% if comments %}
	    {% for comment in comments %}
	      <li class="comment {% cycle 'odd' 'even' %}{% if not comment.is_public %} 'blocked'{% endif %}">
	          <p class="meta"><strong>{{ comment.created_by }}</strong> |
		          <a href="mailto:{{ comment.email_id }}">{{ comment.email_id }}</a>
		          <a href="{{ comment.user_url }}">{{ comment.user_url }}</a> |
	          </p>
	          <div class="body">{{ comment.text }}</div>
	          <p>{{ comment.created_on }}
	          [
	          {% if comment.is_public %}
	            <a href="{% url blogango_admin_comment_block comment.id %}">{{ _("Block") }}</a> |
              {% else %}
                <a href="{% url blogango_admin_comment_approve comment.id %}">{{ _("Approve") }}</a> |
	          {% endif %}
	            <a href="{{ comment.comment_for.get_edit_url }}">{{ comment.comment_for.title }}</a>
	          ]
	          </p>
	      </li>
	    {% endfor %}
    {% else %}
    	{{ _("No comments") }}
    {% endif %}
    </ul>
{% endblock %}